server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          # 开启从注册中心动态创建路由的功能，利用微服务名称进行路由
          enabled: true
      routes:
      # 路由的id,没有规定规则但要求唯一,建议配合服务名
      - id: cloud-provider-payment8001-getPaymentById
        uri: lb://cloud-payment-service
        predicates:
        - Path=/payment/get/**

      - id: cloud-provider-payment8001-discovery
        uri: lb://cloud-payment-service
        predicates:
        - Path=/payment/discovery
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

