#服务端口号
server:
  port: 70

#服务名称
spring:
  application:
    name: consul-consumer-order

  #consul注册中心地址
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: payment-order-80
        service-name: ${spring.application.name}
