server:
  port: 70
eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
ribbon:
  #服务连接的最长时间
  ConnectTimeout: 5000
  #服务连接后返回结果的最长时间
  ReadTimeout:  5000
feign:
  hystrix:
    enabled: true
